package:
    name: elasticsearch
    version: "1.6.0"

source:
    git_rev: v1.6.0
    git_url: https://github.com/elastic/elasticsearch.git

build:
    number: 0

requirements:
    build:
        - apache-maven
