package:
    name: kibana
    version: "4.1.1"

source:
    fn: kibana-4.1.1-linux-x64.tar.gz
    url: https://download.elastic.co/kibana/kibana/kibana-4.1.1-linux-x64.tar.gz
    sha1: d43e039adcea43e1808229b9d55f3eaee6a5edb9
