package:
    name: kibana
    version: "4.1.1"

source:
    fn: kibana-4.1.1-linux-x86.tar.gz
    url: https://download.elastic.co/kibana/kibana/kibana-4.1.1-linux-x86.tar.gz
    sha1: 8f756e680189f991ebdb081178613ec39381a0c9
